### ISSUE TITLE
final

### ISSUE THREAD

**Issue by patyaa** [patyaa/MOSZE_vizsga#5]
Elkészült a projekt a MOSZE vizsgára

**Comment by hegyhati** [comment]
No, meglestem a videokat, meg picit a repot. Hat a MOSZE-s dolgok ott vannak, de ugya a program eleg "minimalista", es akkor nagyon diplomatikusan fogalmazok. A git history is igy ugye eleg minimalis. 2-3 kozott billegek, de mivel utolso vizsga, ne huzzuk, legyen 3.

**Comment by hegyhati** [comment]
a neptun eppen le van halva, de holnap beirom.

**Comment by patyaa** [comment]
Rendben, koszonom szepen
